services:
  backend:
    build:
      context: ./todoapp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    build:
      context: ./todoapp/frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4200:80"
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: "8080"
    depends_on:
      - backend
